# Generated by Django 6.0.7 on 2026-07-21 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BRAND_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BRAND_NAME', models.CharField(max_length=100, unique=True)),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('STATUS', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['BRAND_NAME'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CATEGORY_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CATEGORY_NAME', models.CharField(max_length=100, unique=True)),
                ('CATEGORY_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('STATUS', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['CATEGORY_NAME'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('UOM_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('UOM_NAME', models.CharField(max_length=50, unique=True)),
                ('SHORT_NAME', models.CharField(max_length=20, unique=True)),
                ('STATUS', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'units',
                'ordering': ['UOM_NAME'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ITEM_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ITEM_CODE', models.CharField(editable=False, max_length=20, unique=True)),
                ('ITEM_NAME', models.CharField(max_length=200, unique=True)),
                ('ITEM_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('COST_PRICE', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('MIN_STOCK', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('MAX_STOCK', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('REORDER_LEVEL', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('MORE_DETAIL', models.TextField(blank=True, null=True)),
                ('STATUS', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('BRAND', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.brand')),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
                ('CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('UPDATED_BY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_updated', to=settings.AUTH_USER_MODEL)),
                ('UOM', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unit')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['ITEM_NAME'],
            },
        ),
    ]
