# Generated by Django 6.0.7 on 2026-08-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_voucherdetail_account_code'),
        ('purchases', '0003_alter_purchasedetail_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='account_code',
            field=models.ForeignKey(blank=True, db_column='ACCOUNT_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_accounts', to='accounting.party'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='purchase_code',
            field=models.ForeignKey(blank=True, db_column='PURCHASE_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_codes', to='accounting.party'),
        ),
    ]
