# Generated by Django 6.0.7 on 2026-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchasedetail_weight_kg_purchasedetail_weight_lbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='weight_per_unit',
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in kilograms', max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in pounds (kg × 2.2040)', max_digits=15),
        ),
    ]
