# Generated by Django 6.0.7 on 2026-08-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('sub', models.CharField(choices=[('debtor', 'Debtor'), ('creditor', 'Creditor'), ('expense', 'Expense'), ('inventory', 'Inventory'), ('income', 'Income'), ('bank', 'Bank'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('ntn', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'parties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_column='YEAR', max_length=4)),
                ('vtype', models.CharField(db_column='VTYPE', max_length=5)),
                ('vno', models.IntegerField(db_column='VNO')),
                ('vdate', models.DateField(db_column='VDATE')),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=100, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=1, null=True)),
                ('received_by', models.CharField(blank=True, db_column='RECEIVED_BY', max_length=25, null=True)),
                ('user_no', models.IntegerField(db_column='USER_NO')),
            ],
            options={
                'db_table': 'VOUCHER_M',
                'constraints': [models.UniqueConstraint(fields=('year', 'vtype', 'vno'), name='PK_VM_YRVT_VN')],
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_column='YEAR', max_length=4)),
                ('vtype', models.CharField(db_column='VTYPE', max_length=5)),
                ('vno', models.IntegerField(db_column='VNO')),
                ('vsn', models.IntegerField(db_column='VSN')),
                ('narration', models.CharField(blank=True, db_column='NARRATION', max_length=100, null=True)),
                ('debit', models.DecimalField(db_column='DEBIT', decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(db_column='CREDIT', decimal_places=2, default=0, max_digits=15)),
                ('branch', models.CharField(blank=True, db_column='BRANCH', max_length=10, null=True)),
                ('cheque_no', models.CharField(blank=True, db_column='CHEQUE_NO', max_length=15, null=True)),
                ('cheque_date', models.DateField(blank=True, db_column='CHEQUE_DATE', null=True)),
                ('chq_title', models.CharField(blank=True, db_column='CHQ_TITLE', max_length=50, null=True)),
                ('due', models.IntegerField(blank=True, db_column='DUE', null=True)),
                ('account_code', models.ForeignKey(db_column='ACCOUNT_CODE', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_details', to='accounting.party')),
                ('voucher_master', models.ForeignKey(blank=True, db_column='voucher_master_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.vouchermaster')),
            ],
            options={
                'db_table': 'VOUCHER_D',
                'constraints': [models.UniqueConstraint(fields=('year', 'vtype', 'vno', 'vsn'), name='PK_VD_YRVT_VN_VS')],
            },
        ),
    ]
