# Generated by Django 6.0.7 on 2026-08-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdetail',
            name='account_code',
            field=models.ForeignKey(db_column='ACCOUNT_CODE', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_details', to='accounting.party'),
        ),
    ]
