# Generated by Django 6.0.7 on 2026-08-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleOrder', '0002_alter_saleorderdetail_item_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderdetail',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in kg (qty × weight_per_unit)', max_digits=15),
        ),
        migrations.AddField(
            model_name='saleorderdetail',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in lbs (weight_kg × 2.2040)', max_digits=15),
        ),
        migrations.AddField(
            model_name='saleorderdetail',
            name='weight_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Weight per unit (kg) – taken from item at order time', max_digits=10),
        ),
    ]
