# Generated by Django 6.0.7 on 2026-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleOrder', '0003_saleorderdetail_weight_kg_saleorderdetail_weight_lbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderdetail',
            name='weight_per_unit',
        ),
        migrations.AlterField(
            model_name='saleorderdetail',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in kg (user entered)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleorderdetail',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in lbs (auto‑computed from weight_kg)', max_digits=15),
        ),
    ]
