# Generated by Django 6.0.7 on 2026-07-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=100, unique=True)),
                ('USER_PWD', models.CharField(max_length=255)),
                ('USER_ROLE', models.CharField(max_length=50)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
