# Generated by Django 6.0.7 on 2026-08-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_PWD',
            field=models.CharField(db_column='USER_PWD', max_length=255),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='USER_PWD',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CREATED_AT',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='IS_ACTIVE',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UPDATED_AT',
            field=models.DateTimeField(auto_now=True, db_column='UPDATED_AT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_ID',
            field=models.BigAutoField(db_column='USER_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_NAME',
            field=models.CharField(db_column='USER_NAME', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_ROLE',
            field=models.CharField(db_column='USER_ROLE', default='user', max_length=50),
        ),
    ]
