# Generated by Django 6.0.7 on 2026-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cih_code', models.CharField(blank=True, max_length=10, null=True)),
                ('freight_code', models.CharField(blank=True, max_length=10, null=True)),
                ('t_o_code', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_code_mix', models.CharField(blank=True, max_length=10, null=True)),
                ('cashsale_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sample_code', models.CharField(blank=True, max_length=10, null=True)),
                ('cashdisc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('debtor_code', models.CharField(blank=True, max_length=10, null=True)),
                ('creditor_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lgr_date_from', models.DateField(blank=True, null=True)),
                ('lgr_date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Setup',
                'verbose_name_plural': 'Account Setups',
                'db_table': 'AC_SETUP',
            },
        ),
    ]
