# Generated by Django 6.0.7 on 2026-08-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ac_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acsetup',
            options={'managed': False},
        ),
    ]
