# Generated by Django 6.0.7 on 2026-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VType',
            fields=[
                ('vtype', models.CharField(db_column='vtype', max_length=5, primary_key=True, serialize=False)),
                ('vtype_description', models.CharField(db_column='vtype_description', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Voucher Type',
                'verbose_name_plural': 'Voucher Types',
                'db_table': 'vtypes',
            },
        ),
    ]
