# Generated by Django 6.0.7 on 2026-08-04 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0002_remove_item_brand_remove_item_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(db_column='VTYPE', max_length=5)),
                ('vno', models.IntegerField(db_column='VNO')),
                ('vdate', models.DateField(db_column='VDATE')),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=100, null=True)),
                ('stts', models.CharField(db_column='STTS', default='A', max_length=1)),
                ('supplier', models.ForeignKey(blank=True, db_column='SUPPLIER_ID', limit_choices_to={'sub': 'creditor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='accounting.party')),
                ('user_no', models.ForeignKey(blank=True, db_column='USER_NO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PO_M',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(db_column='VTYPE', max_length=5)),
                ('vno', models.IntegerField(db_column='VNO')),
                ('vsn', models.IntegerField(db_column='VSN')),
                ('qty', models.DecimalField(db_column='QTY', decimal_places=3, max_digits=11)),
                ('rate', models.DecimalField(db_column='RATE', decimal_places=4, max_digits=13)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('item_code', models.ForeignKey(blank=True, db_column='ITEM_CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_details', to='inventory.item')),
                ('uom', models.ForeignKey(blank=True, db_column='UOM_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_details', to='inventory.unit')),
                ('purchase_order_master', models.ForeignKey(db_column='purchase_order_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='purchaseOrders.purchaseordermaster')),
            ],
            options={
                'db_table': 'PO_D',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseordermaster',
            constraint=models.UniqueConstraint(fields=('vtype', 'vno'), name='PK_VTYPNO_POM'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderdetail',
            constraint=models.UniqueConstraint(fields=('vtype', 'vno', 'vsn'), name='PK_VTYPNOSN_POD'),
        ),
    ]
