# Generated by Django 6.0.7 on 2026-08-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_voucherdetail_account_code'),
        ('inventory', '0002_remove_item_brand_remove_item_category_and_more'),
        ('purchaseOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='item_code',
            field=models.ForeignKey(blank=True, db_column='ITEM_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_details', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='uom',
            field=models.ForeignKey(blank=True, db_column='UOM_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_details', to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='purchaseordermaster',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='SUPPLIER_ID', limit_choices_to={'sub': 'creditor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='accounting.party'),
        ),
    ]
