# Generated by Django 6.0.7 on 2026-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrders', '0003_purchaseorderdetail_weight_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderdetail',
            name='weight_per_unit',
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in kg (entered by user)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total weight in lbs (auto‑calculated: kg × 2.2046)', max_digits=15),
        ),
    ]
