# Generated by Django 6.0.7 on 2026-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=20, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['code'],
            },
        ),
    ]
