# Generated by Django 6.0.7 on 2026-08-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0002_remove_item_brand_remove_item_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(db_column='VTYPE', max_length=5)),
                ('vno', models.IntegerField(db_column='VNO')),
                ('vdate', models.DateField(db_column='VDATE')),
                ('dc_no', models.CharField(blank=True, db_column='DC_NO', max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=100, null=True)),
                ('discount', models.DecimalField(db_column='DISCOUNT', decimal_places=2, default=0, max_digits=10)),
                ('stts', models.CharField(db_column='STTS', default='A', max_length=1)),
                ('voucher_created', models.BooleanField(default=False)),
                ('account_code', models.ForeignKey(blank=True, db_column='ACCOUNT_CODE', limit_choices_to={'sub': 'debtor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_accounts', to='accounting.party')),
                ('sale_code', models.ForeignKey(blank=True, db_column='SALE_CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_codes', to='accounting.party')),
                ('user_no', models.ForeignKey(blank=True, db_column='USER_NO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'INV_M',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(db_column='VTYPE', max_length=5)),
                ('vno', models.IntegerField(db_column='VNO')),
                ('vsn', models.IntegerField(db_column='VSN')),
                ('qty', models.DecimalField(db_column='QTY', decimal_places=3, default=0, max_digits=11)),
                ('rate', models.DecimalField(db_column='RATE', decimal_places=4, default=0, max_digits=13)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, default=0, max_digits=10)),
                ('item_code', models.ForeignKey(blank=True, db_column='ITEM_CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_details', to='inventory.item')),
                ('uom', models.ForeignKey(blank=True, db_column='UOM_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_details', to='inventory.unit')),
                ('sale_master', models.ForeignKey(blank=True, db_column='sale_master_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.salemaster')),
            ],
            options={
                'db_table': 'INV_D',
            },
        ),
        migrations.AddConstraint(
            model_name='salemaster',
            constraint=models.UniqueConstraint(fields=('vtype', 'vno'), name='PK_VTYPNO_SALEM'),
        ),
        migrations.AddConstraint(
            model_name='saledetail',
            constraint=models.UniqueConstraint(fields=('vtype', 'vno', 'vsn'), name='PK_VTYPNOSN_SALED'),
        ),
    ]
