# Generated by Django 6.0.7 on 2026-08-07 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_brand_remove_item_category_and_more'),
        ('sales', '0002_saledetail_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='item_code',
            field=models.ForeignKey(blank=True, db_column='ITEM_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='inventory.item'),
        ),
    ]
