# Generated by Django 6.0.7 on 2026-08-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_voucherdetail_account_code'),
        ('sales', '0003_alter_saledetail_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemaster',
            name='account_code',
            field=models.ForeignKey(blank=True, db_column='ACCOUNT_CODE', limit_choices_to={'sub': 'debtor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_accounts', to='accounting.party'),
        ),
        migrations.AlterField(
            model_name='salemaster',
            name='sale_code',
            field=models.ForeignKey(blank=True, db_column='SALE_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_codes', to='accounting.party'),
        ),
    ]
