# Generated by Django 6.0.7 on 2026-08-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_saledetail_weight_kg_saledetail_weight_lbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='weight_per_unit',
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
